workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: iOS SouArtista
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: aplicativo.souartista
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        VITE_SUPABASE_URL: "https://wjutvzmnvemrplpwbkyf.supabase.co"
        VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdXR2em1udmVtcnBscHdia3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MDAyNjQsImV4cCI6MjA3OTE3NjI2NH0.JiOuFZcjDLvh7_gpfj7b_Zv5bK_8G2KmHAketLceCCk"
        VITE_SUPABASE_PROJECT_ID: "wjutvzmnvemrplpwbkyf"
      node: v20
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install dependencies
        script: npm install
      
      - name: Install capacitor-assets
        script: npm install -g @capacitor/assets
      
      - name: Build web assets
        script: npm run build
      
      - name: Add and Sync Capacitor iOS
        script: |
          rm -rf ios
          PLATFORM=ios npx cap add ios
          PLATFORM=ios npx cap sync ios
      
      - name: Set iOS version
        script: |
          cd ios/App
          agvtool new-version -all $PROJECT_BUILD_NUMBER
      
      - name: Generate App Icons and Splash Screens
        script: npx capacitor-assets generate --ios
      
      - name: Install CocoaPods
        script: cd ios/App && pod install
      
      - name: Initialize keychain
        script: keychain initialize
      
      - name: Add certificates to keychain
        script: keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
