workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: iOS SouArtista
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: aplicativo.souartista
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        VITE_SUPABASE_URL: "https://wjutvzmnvemrplpwbkyf.supabase.co"
        VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdXR2em1udmVtcnBscHdia3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MDAyNjQsImV4cCI6MjA3OTE3NjI2NH0.JiOuFZcjDLvh7_gpfj7b_Zv5bK_8G2KmHAketLceCCk"
        VITE_SUPABASE_PROJECT_ID: "wjutvzmnvemrplpwbkyf"
      node: v20
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install dependencies
        script: npm install
      
      - name: Install capacitor-assets
        script: npm install -g @capacitor/assets
      
      - name: Build web assets
        script: npm run build
      
      - name: Add and Sync Capacitor iOS
        script: |
          rm -rf ios
          PLATFORM=ios npx cap add ios
          PLATFORM=ios npx cap sync ios
      
      - name: Copy GoogleService-Info.plist
        script: cp resources/GoogleService-Info.plist ios/App/App/
      
      - name: Add Firebase to Podfile
        script: |
          # Add Firebase Messaging pod to Podfile
          cd ios/App
          cat >> Podfile << 'EOF'

          # Firebase for Push Notifications
          pod 'Firebase/Messaging'
          EOF
      
      - name: Configure AppDelegate for Firebase Messaging
        script: |
          # Create AppDelegate.swift with Firebase initialization
          cat > ios/App/App/AppDelegate.swift << 'EOF'
          import UIKit
          import Capacitor
          import FirebaseCore
          import FirebaseMessaging

          @UIApplicationMain
          class AppDelegate: UIResponder, UIApplicationDelegate, MessagingDelegate {

              var window: UIWindow?

              func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                  // Initialize Firebase
                  FirebaseApp.configure()
                  
                  // Set messaging delegate
                  Messaging.messaging().delegate = self
                  
                  // Register for remote notifications
                  application.registerForRemoteNotifications()
                  
                  return true
              }

              func applicationWillResignActive(_ application: UIApplication) {
              }

              func applicationDidEnterBackground(_ application: UIApplication) {
              }

              func applicationWillEnterForeground(_ application: UIApplication) {
              }

              func applicationDidBecomeActive(_ application: UIApplication) {
              }

              func applicationWillTerminate(_ application: UIApplication) {
              }

              func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
                  return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
              }

              func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
                  return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
              }

              // MARK: - Push Notifications (APNs)
              func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
                  // Pass APNs token to Firebase
                  Messaging.messaging().apnsToken = deviceToken
                  // Also notify Capacitor
                  NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
              }

              func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
                  print("Failed to register for remote notifications: \(error)")
                  NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
              }
              
              // MARK: - Firebase Messaging Delegate
              func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
                  print("Firebase FCM token: \(fcmToken ?? "nil")")
                  // Token will be handled by Capacitor Firebase Messaging plugin
              }
          }
          EOF
      
      - name: Add Push Notification Entitlement
        script: |
          cat > ios/App/App/App.entitlements << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>aps-environment</key>
            <string>production</string>
          </dict>
          </plist>
          EOF
          
          # Add entitlements to Xcode project
          ruby <<RUBY
          require 'xcodeproj'
          project_path = 'ios/App/App.xcodeproj'
          project = Xcodeproj::Project.open(project_path)
          target = project.targets.first
          target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'App/App.entitlements'
          end
          project.save
          RUBY
      
      - name: Set iOS version
        script: |
          cd ios/App
          agvtool new-version -all $PROJECT_BUILD_NUMBER
      
      - name: Generate App Icons and Splash Screens
        script: npx capacitor-assets generate --ios
      
      - name: Install CocoaPods
        script: cd ios/App && pod install
      
      - name: Initialize keychain
        script: keychain initialize
      
      - name: Add certificates to keychain
        script: keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
